### ISSUE TITLE
sample data doesnt work due to non numeric chromosomes being encoded as NA

### ISSUE THREAD

**Issue by YPHa** [piquelab/QuASAR#2]
due to the line:
chrList <- paste("chr", sort(as.numeric(gsub("chr", "", chrList))), sep="")
from:
scripts/convertPileupToQuasar.R
chromosomes such as X get encoded to NA

a worked around this problem by using the naturalsort library:
library('naturalsort')
chrList <- naturalsort(chrList, decreasing=FALSE, na.last=NA)

**Comment by ctharve** [comment]
After realizing that reordering the chromosomes was not necessary, we removed those lines from the script. Thank you for pointing this out.
