### ISSUE TITLE
Wrong pre-processing allele frequency BED format

### ISSUE THREAD

**Issue by MrFlick** [piquelab/QuASAR#4]
In the main README, under the "Pileups & cleaned pileups" section, it says that the BED file should contain "1-3) coordinate, 4) SNP ID, 5) allele frequency". However, the sample R script that reads in the intersected data ([convertPileupToQuasar.R](https://github.com/piquelab/QuASAR/blob/master/scripts/convertPileupToQuasar.R)) has columns for

    names(pileup) <- c("chr", "pos-1", "pos", "ref", "num.reads", "read.alleles",
    	"read.quality", "rsID", "TKG.Ref", "alt", "af")

So it looks like the BED file should actually have 7 columns: 1-3) coordinate, 4) SNP ID, 5) ref allele 6) alt allele 5) allele frequency

**Comment by gmoyerbrailean** [comment]
Thanks for pointing this out! I have updated the README to reflect how this file should be formatted.
